version: '3'
services: 
  SH00:
    image: oracle/database/gsm:19.3.0-ee
    container_name: SH00
    volumes:
      - "/Users/sean.scott/oradata/SH00:/opt/oracle/oradata"
      - "/Users/sean.scott/shard:/opt/oracle/scripts"
    environment:
      CONTAINER_NAME: SH00
      DB_UNIQUE_NAME: SH00
      DG_CONFIG: NONE
      DG_TARGET: 
      GDS_USER: gdsadmin
      GDS_PASS: oracle
      GSM_PASS: oracle
      GSM_PORT: 1571
      GSM_REGION: na,eu,asia
      ORACLE_PDB: SH00PDB1
      ORACLE_PWD: oracle
      ORACLE_SID: SH00
      ROLE: PRIMARY
      SHARD_DB: SH00PDB1
      SHARD_DBNAME: shardcat
      SHARD_DIRECTOR: sharddir1
      SHARD_ROLE: CATALOG
    ports:
      - "1200:1521"
      - "1710:1571"
      - "1720:1572"

  SH11:
    image: oracle/database/gsm:19.3.0-ee
    container_name: SH11
    volumes:
      - "/Users/sean.scott/oradata/SH11:/opt/oracle/oradata"
      - "/Users/sean.scott/shard:/opt/oracle/scripts"
    environment:
      CONTAINER_NAME: SH11
      DB_UNIQUE_NAME: SH11
      DG_CONFIG: SH1
      DG_TARGET: SH21
      GDS_USER: gdsadmin
      GDS_PASS: oracle
      GSM_PASS: oracle
      GSM_PORT: 
      GSM_REGION: na
      ORACLE_PDB: SH11PDB1
      ORACLE_PWD: oracle
      ORACLE_SID: SH11
      ROLE: PRIMARY
      SHARD_DB: 
      SHARD_DBNAME: 
      SHARD_DIRECTOR: 
      SHARD_ROLE: 
    ports:
      - "1201:1521"
      - "1711:1571"
      - "1721:1572"

  SH12:
    image: oracle/database/gsm:19.3.0-ee
    container_name: SH12
    volumes:
      - "/Users/sean.scott/oradata/SH12:/opt/oracle/oradata"
      - "/Users/sean.scott/shard:/opt/oracle/scripts"
    environment:
      CONTAINER_NAME: SH12
      DB_UNIQUE_NAME: SH12
      DG_CONFIG: SH2
      DG_TARGET: SH22
      GDS_USER: gdsadmin
      GDS_PASS: oracle
      GSM_PASS: oracle
      GSM_PORT: 1572
      GSM_REGION: eu
      ORACLE_PDB: SH12PDB1
      ORACLE_PWD: oracle
      ORACLE_SID: SH12
      ROLE: PRIMARY
      SHARD_DB: SH00PDB1
      SHARD_DBNAME: 
      SHARD_DIRECTOR: sharddir2
      SHARD_ROLE: DIRECTOR
    ports:
      - "1203:1521"
      - "1713:1571"
      - "1723:1572"

  SH13:
    image: oracle/database/gsm:19.3.0-ee
    container_name: SH13
    volumes:
      - "/Users/sean.scott/oradata/SH13:/opt/oracle/oradata"
      - "/Users/sean.scott/shard:/opt/oracle/scripts"
    environment:
      CONTAINER_NAME: SH13
      DB_UNIQUE_NAME: SH13
      DG_CONFIG: SH3
      DG_TARGET: SH23
      GDS_USER: gdsadmin
      GDS_PASS: oracle
      GSM_PASS: oracle
      GSM_PORT: 
      GSM_REGION: asia
      ORACLE_PDB: SH13PDB1
      ORACLE_PWD: oracle
      ORACLE_SID: SH13
      ROLE: PRIMARY
      SHARD_DB: 
      SHARD_DBNAME: 
      SHARD_DIRECTOR: 
      SHARD_ROLE: 
    ports:
      - "1205:1521"
      - "1715:1571"
      - "1725:1572"

  SH21:
    image: oracle/database/gsm:19.3.0-ee
    container_name: SH21
    volumes:
      - "/Users/sean.scott/oradata/SH21:/opt/oracle/oradata"
      - "/Users/sean.scott/shard:/opt/oracle/scripts"
    environment:
      CONTAINER_NAME: SH21
      DB_UNIQUE_NAME: SH21
      DG_CONFIG: SH1
      DG_TARGET: SH11
      GDS_USER: 
      GDS_PASS: 
      GSM_PASS: 
      GSM_PORT: 
      GSM_REGION: na
      ORACLE_PDB: SH11PDB1
      ORACLE_PWD: oracle
      ORACLE_SID: SH11
      ROLE: STANDBY
      SHARD_DB: 
      SHARD_DBNAME: 
      SHARD_DIRECTOR: 
      SHARD_ROLE: 
    ports:
      - "1202:1521"
      - "1712:1571"
      - "1722:1572"

  SH22:
    image: oracle/database/gsm:19.3.0-ee
    container_name: SH22
    volumes:
      - "/Users/sean.scott/oradata/SH22:/opt/oracle/oradata"
      - "/Users/sean.scott/shard:/opt/oracle/scripts"
    environment:
      CONTAINER_NAME: SH22
      DB_UNIQUE_NAME: SH22
      DG_CONFIG: SH2
      DG_TARGET: SH12
      GDS_USER: 
      GDS_PASS: 
      GSM_PASS: 
      GSM_PORT: 
      GSM_REGION: eu
      ORACLE_PDB: SH12PDB1
      ORACLE_PWD: oracle
      ORACLE_SID: SH12
      ROLE: STANDBY
      SHARD_DB: 
      SHARD_DBNAME: 
      SHARD_DIRECTOR: 
      SHARD_ROLE: 
    ports:
      - "1204:1521"
      - "1714:1571"
      - "1724:1572"

  SH23:
    image: oracle/database/gsm:19.3.0-ee
    container_name: SH23
    volumes:
      - "/Users/sean.scott/oradata/SH23:/opt/oracle/oradata"
      - "/Users/sean.scott/shard:/opt/oracle/scripts"
    environment:
      CONTAINER_NAME: SH23
      DB_UNIQUE_NAME: SH23
      DG_CONFIG: SH3
      DG_TARGET: SH13
      GDS_USER: 
      GDS_PASS: 
      GSM_PASS: 
      GSM_PORT: 
      GSM_REGION: asia
      ORACLE_PDB: SH13PDB1
      ORACLE_PWD: oracle
      ORACLE_SID: SH13
      ROLE: STANDBY
      SHARD_DB: 
      SHARD_DBNAME: 
      SHARD_DIRECTOR: 
      SHARD_ROLE: 
    ports:
      - "1206:1521"
      - "1716:1571"
      - "1726:1572"

  SH00:
    image: oracle/database/gsm:19.3.0-ee
    container_name: SH00
    volumes:
      - "/Users/sean.scott/oradata/SH00:/opt/oracle/oradata"
      - "/Users/sean.scott/shard:/opt/oracle/scripts"
    environment:
      CONTAINER_NAME: SH00
      DG_CONFIG: NONE
      DG_TARGET: 
      GDS_USER: gdsadmin
      GDS_PASS: oracle
      GSM_PASS: oracle
      GSM_PORT: 1571
      GSM_REGION: na,eu,asia
      ORACLE_PDB: SH00PDB1
      ORACLE_PWD: oracle
      ORACLE_SID: SH00
      ROLE: PRIMARY
      SHARD_DB: SH00PDB1
      SHARD_DBNAME: shardcat
      SHARD_DIRECTOR: sharddir1
      SHARD_ROLE: CATALOG
    ports:
      - "1200:1521"
      - "1710:1571"
      - "1720:1572"

  SH11:
    image: oracle/database/gsm:19.3.0-ee
    container_name: SH11
    volumes:
      - "/Users/sean.scott/oradata/SH11:/opt/oracle/oradata"
      - "/Users/sean.scott/shard:/opt/oracle/scripts"
    environment:
      CONTAINER_NAME: SH11
      DG_CONFIG: SH1
      DG_TARGET: SH21
      GDS_USER: gdsadmin
      GDS_PASS: oracle
      GSM_PASS: oracle
      GSM_PORT: 
      GSM_REGION: na
      ORACLE_PDB: SH11PDB1
      ORACLE_PWD: oracle
      ORACLE_SID: SH11
      ROLE: PRIMARY
      SHARD_DB: 
      SHARD_DBNAME: 
      SHARD_DIRECTOR: 
      SHARD_ROLE: 
    ports:
      - "1201:1521"
      - "1711:1571"
      - "1721:1572"

  SH12:
    image: oracle/database/gsm:19.3.0-ee
    container_name: SH12
    volumes:
      - "/Users/sean.scott/oradata/SH12:/opt/oracle/oradata"
      - "/Users/sean.scott/shard:/opt/oracle/scripts"
    environment:
      CONTAINER_NAME: SH12
      DG_CONFIG: SH2
      DG_TARGET: SH22
      GDS_USER: gdsadmin
      GDS_PASS: oracle
      GSM_PASS: oracle
      GSM_PORT: 1572
      GSM_REGION: eu
      ORACLE_PDB: SH12PDB1
      ORACLE_PWD: oracle
      ORACLE_SID: SH12
      ROLE: PRIMARY
      SHARD_DB: SH00PDB1
      SHARD_DBNAME: 
      SHARD_DIRECTOR: sharddir2
      SHARD_ROLE: DIRECTOR
    ports:
      - "1203:1521"
      - "1713:1571"
      - "1723:1572"

  SH13:
    image: oracle/database/gsm:19.3.0-ee
    container_name: SH13
    volumes:
      - "/Users/sean.scott/oradata/SH13:/opt/oracle/oradata"
      - "/Users/sean.scott/shard:/opt/oracle/scripts"
    environment:
      CONTAINER_NAME: SH13
      DG_CONFIG: SH3
      DG_TARGET: SH23
      GDS_USER: gdsadmin
      GDS_PASS: oracle
      GSM_PASS: oracle
      GSM_PORT: 
      GSM_REGION: asia
      ORACLE_PDB: SH13PDB1
      ORACLE_PWD: oracle
      ORACLE_SID: SH13
      ROLE: PRIMARY
      SHARD_DB: 
      SHARD_DBNAME: 
      SHARD_DIRECTOR: 
      SHARD_ROLE: 
    ports:
      - "1205:1521"
      - "1715:1571"
      - "1725:1572"

  SH21:
    image: oracle/database/gsm:19.3.0-ee
    container_name: SH21
    volumes:
      - "/Users/sean.scott/oradata/SH21:/opt/oracle/oradata"
      - "/Users/sean.scott/shard:/opt/oracle/scripts"
    environment:
      CONTAINER_NAME: SH21
      DG_CONFIG: SH1
      DG_TARGET: SH11
      GDS_USER: 
      GDS_PASS: 
      GSM_PASS: 
      GSM_PORT: 
      GSM_REGION: na
      ORACLE_PDB: SH11PDB1
      ORACLE_PWD: oracle
      ORACLE_SID: SH11
      ROLE: STANDBY
      SHARD_DB: 
      SHARD_DBNAME: 
      SHARD_DIRECTOR: 
      SHARD_ROLE: 
    ports:
      - "1202:1521"
      - "1712:1571"
      - "1722:1572"

  SH22:
    image: oracle/database/gsm:19.3.0-ee
    container_name: SH22
    volumes:
      - "/Users/sean.scott/oradata/SH22:/opt/oracle/oradata"
      - "/Users/sean.scott/shard:/opt/oracle/scripts"
    environment:
      CONTAINER_NAME: SH22
      DG_CONFIG: SH2
      DG_TARGET: SH12
      GDS_USER: 
      GDS_PASS: 
      GSM_PASS: 
      GSM_PORT: 
      GSM_REGION: eu
      ORACLE_PDB: SH12PDB1
      ORACLE_PWD: oracle
      ORACLE_SID: SH12
      ROLE: STANDBY
      SHARD_DB: 
      SHARD_DBNAME: 
      SHARD_DIRECTOR: 
      SHARD_ROLE: 
    ports:
      - "1204:1521"
      - "1714:1571"
      - "1724:1572"

  SH23:
    image: oracle/database/gsm:19.3.0-ee
    container_name: SH23
    volumes:
      - "/Users/sean.scott/oradata/SH23:/opt/oracle/oradata"
      - "/Users/sean.scott/shard:/opt/oracle/scripts"
    environment:
      CONTAINER_NAME: SH23
      DG_CONFIG: SH3
      DG_TARGET: SH13
      GDS_USER: 
      GDS_PASS: 
      GSM_PASS: 
      GSM_PORT: 
      GSM_REGION: asia
      ORACLE_PDB: SH13PDB1
      ORACLE_PWD: oracle
      ORACLE_SID: SH13
      ROLE: STANDBY
      SHARD_DB: 
      SHARD_DBNAME: 
      SHARD_DIRECTOR: 
      SHARD_ROLE: 
    ports:
      - "1206:1521"
      - "1716:1571"
      - "1726:1572"

